Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/03/2024
Var
// Seção de Declarações das variáveis 
 media: real
 classificacao: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
media <- (nota1 + nota2 + trabalho) / 3
SE (media >= 6) ENTAO

Fimalgoritmo